- hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Update package manager cache
      yum:
        update_cache: yes

    - name: Install Apache web server
      yum:
        name: httpd
        state: present

    - name: Start Apache service
      service:
        name: httpd
        state: started

    - name: Enable Apache service
      service:
        name: httpd
        enabled: yes

    - name: copy index.html file
      copy:
        src: /etc/ansible/index.html
        dest: /var/www/html/index.html

    - name: Restart httpd service
      service:
        name: httpd
        state: restarted